name: Demo

on: push

jobs:
  hello:
    name: Hello
    runs-on: ubuntu:latest
    steps: 
      - name: Checkout
        uses: actions/checkout/v2
        run: ls
        run: echo "Hello World"
        shell: bash
