name: Main

on:
  schedule:
    - cron: '*/10 * * * *' # Run every day at midnight UTC
  push: 
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - run: | 
         ls
         pwd
         sudo su
         echo '$GITHUB_EVENT_NAME'
      - run: echo "hello"
