name: Demo

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC
  push: 
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-18.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - run: | 
         ls
         pwd
         sudo su
         cat Helloworld.txt
      - run: echo "hello"
