name: Develop

on:
  push:
  schedule:
    - cron: '*/14 * * * *' # Run every day at midnight UTC


jobs:
  hello:
    name: Hello
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - run: | 
         ls
         pwd
         sudo su
      - run: echo "hello"
