name: Demo

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-18.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - run: | 
         ls
         pwd
         sudo su
         cat Helloworld.txt
      - run: echo "hello"
